//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dawan_WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SerieDLL_EF.Models.UserApp UserRemain {
            get {
                return ((global::SerieDLL_EF.Models.UserApp)(this["UserRemain"]));
            }
            set {
                this["UserRemain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string token {
            get {
                return ((string)(this["token"]));
            }
            set {
                this["token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<SerieDLL_EF.Models.Serie> ExportSerie {
            get {
                return ((global::System.Collections.Generic.List<SerieDLL_EF.Models.Serie>)(this["ExportSerie"]));
            }
            set {
                this["ExportSerie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<SerieDLL_EF.Models.Episode> ExportEpisode {
            get {
                return ((global::System.Collections.Generic.List<SerieDLL_EF.Models.Episode>)(this["ExportEpisode"]));
            }
            set {
                this["ExportEpisode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<SerieDLL_EF.Models.Acteur> ExportActeur {
            get {
                return ((global::System.Collections.Generic.List<SerieDLL_EF.Models.Acteur>)(this["ExportActeur"]));
            }
            set {
                this["ExportActeur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<SerieDLL_EF.Models.Personnage> ExportPersonnage {
            get {
                return ((global::System.Collections.Generic.List<SerieDLL_EF.Models.Personnage>)(this["ExportPersonnage"]));
            }
            set {
                this["ExportPersonnage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<SerieDLL_EF.Models.Saison> ExportSaison {
            get {
                return ((global::System.Collections.Generic.List<SerieDLL_EF.Models.Saison>)(this["ExportSaison"]));
            }
            set {
                this["ExportSaison"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<SerieDLL_EF.Models.Note> ExportNote {
            get {
                return ((global::System.Collections.Generic.List<SerieDLL_EF.Models.Note>)(this["ExportNote"]));
            }
            set {
                this["ExportNote"] = value;
            }
        }
    }
}
